logging:
  file:
    name: my.log
  level:
    com:
      ylesb:
        springboot: DEBUG
  pattern:
    console: '%d{yyyy/MM/dd-HH:mm:ss} [%thread] %-5level %logger- %msg%n'
    file: '%d{yyyy/MM/dd-HH:mm} [%thread] %-5level %logger- %msg%n'
server:
  port: 8088
spring:
  servlet:
    multipart:
      enabled: true
      location: F:/upload
      max-file-size: 20MB
      max-request-size: 20MB
  mvc:
  static-path-pattern: /faceimg/**
  jackson:
    parser:
      allow-numeric-leading-zeros: true
    date-format: yyyy-MM-dd
  time-zone: GMT+8
  serialization:
   write-dates-as-timestamps: false
  datasource:
   name: test  #数据库名
   url: jdbc:mysql://116.62.110.115:3306/facesign #url
   username: facesign  #用户名
   password: 99d44172db8d6d58  #密码
   driver-class-name: com.mysql.cj.jdbc.Driver  #数据库链接驱动
mybatis:
  mapper-locations: classpath:mapper/*.xml  #配置映射文件
  type-aliases-package: com.ylesb.bsfs.mapper #配置实体类
upload:
  picture:
    path: F:/upload

